name: Build APK
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_API_LEVEL: 34
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.20-8/x64
      BUILDOZER_WARN_ON_ROOT: 0
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: DigonIO/buildozer-action@v1
        with:
          workdir: .
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
